### ISSUE TITLE
Broken url to generator

### ISSUE THREAD

**Issue by zyzo** [fossasia/api.fossasia.net#1]
I wanted to find links to the generator but the link I found seems to be outdated. Or is it just the server config ? Anw the link just redirects to FOSSASIA github page : 
      http://fossasia.net/api/generator/index.html

Here are where I found it : 
       http://blog.fossasia.org/tags/fossasia-api
       http://www.google-melange.com/gci/task/view/google/gci2014/5830616041914368
       http://google-melange.appspot.com/gci/task/view/google/gci2014/5231986905972736

**Comment by ty221** [comment]
Yes, unfortunately, you're right - this link doesn't work anymore. @andibraeu has changed location of our API, I do not have access to its server, so I can't investigate this matter. I am sure @andibraeu or @mariobehling can help us in this case and fix broken urls in articles.

**Comment by andibraeu** [comment]
> Yes, unfortunately, you're right - this link doesn't work anymore. @andibraeu has changed location of our API, I do not have access to its server, so I can't investigate this matter. I am sure @andibraeu or @mariobehling can help us in this case and fix broken urls in articles
> 

It's there now: http://api.fossasia.org/generator

Sorry, forgot to change it in the blog post. Could you please do it?

**Comment by ty221** [comment]
@andibraeu I've changed this in the blog post. Can't work on Melange tasks. I think, we can close this bug now. @zyzo thanks for reporting!
