### ISSUE TITLE
Which features do we want to implement? Which ones can be part of the summer project?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/api.fossasia.net#10]
Please list features to be implemented here.

**Comment by zyzo** [comment]
List of features in chronological order in my summer project : 

* **Calendar service** : 
     * ics feeds collector & aggregator, 
     * community event calendar & community news panel.
* **Community map enhancement** : 
    * filter by country / technical areas.
    * (using calendar service) add info about latest/upcoming event/news on the map marker for each community.
* **Statistic service** : 
    * number of registered communities
    * percentage of communities per countries (pie chart)
    * percentage of communities per tech area (also pie chart)
    * community active period panel (like the one in github), based on news and events. 
    * number of web services deployed in total, and web services types (pie chart)
* **API documentation**

As for features that we can implement but not already listed, there are these extracted from @andi [project proposal](http://labs.fossasia.org/posts/toolbox-fossasia-api.html) : 

* **Extensions**
      * extend FOSSASIA API specs to provide information about services (e.g. web service, mail servers, etc), see api.freifunk.net for inspiration
      * create a web service to get parts of API files, based on geo or content filters
      * build an overview about API files and validate them
* **Visualization**:
      * a framework to easily building charts of API data
      * Euler charts to display by countries, metacommunities, cities
      * Pie-Chart: how to contact communities (Facebook, Jabber, IRC, usw..)

The final goal is to create something useful and popular enough to connect to more communities with the API.

**Comment by andibraeu** [comment]
That sounds good!

We should have a chat about our repo structure these days. There are several repos for our API, because it's just a collection of tools. We should talk, where you can submit code for your extensions. Then you can begin to commit regularly (daily).

We can also ask @mojoaxel He already did some work on visualizations for the Freifunk API.

**Comment by zyzo** [comment]
For ics merger script (#8), there is [feed.api.fossasia.net](fossasia/api.fossasia.net) which already contains a rss merger. Should we put it there ? By the way, shoud  we combine `feed.api.fossasia.net`  and other api-related services to `api.fossasia.net` ?

For others tasks the code destination really depend, Some could go to `fossasia.github.io`. For such tasks I can work on another branch and open pull requests.

@mojoaxel Could you share what did you work on ?

**Comment by mojoaxel** [comment]
@zyzo You can find my (very early) experiments here: https://github.com/mojoaxel/status.freifunk.net

**Comment by andibraeu** [comment]
Am Freitag, den 22.05.2015, 08:33 -0700 schrieb DANG HAI AN:
> For ics merger script (#8), there is feed.api.fossasia.net which 
> already contains a rss merger. Should we put it there ? By the way, 
> shoud we combine feed.api.fossasia.net and other api-related 
> services to api.fossasia.net ?

no, when we began with freifunk API we decided to separate
repositories:

api.fossasia.net: for specs and generator
directory.api.fossasia.net: the directory
common.api.fossasia.net: tools like the collector and other
contributions. here you could add the ics merger
feed.api.fossasia.net: rss feed aggregator
cmap.api.fossasia.net: community map

> For others tasks the code destination really depend, Some could go 
> to fossasia.github.io. For such tasks I can work on another branch 
> and open pull requests.

please use the existing repos. As we also want to port your
developments back to the freifunk API we should have standalone tools,
nothing included to special pages.
If necessary, just write docs how to integrate your tools.

**Comment by zyzo** [comment]
@mojoaxel Looks nice, thanks for sharing ! Do you have any further plan with this ?

@andibraeu Should I put my experimental work on a fossasia repo ? For instance I'm writing a ics parser/merger debugging tool that I want to share.

**Comment by mariobehling** [comment]
@zyzo please add new features into a separate branch until they reach a stable stage.

**Comment by mariobehling** [comment]
@zyzo Looking over your list again, it seems that most of the items come as a requirement of the project. Also, andi added idea. Apart from that documentation is not a feature.

Let's get to the next stage and show us, what cool ideas you can come up with as well. E.g how about integration of a community twitter map with loklak? It's just an example, but it would be awesome to see some more ambitious and exciting stuff as well.

**Comment by zyzo** [comment]
Can I have access to other repos to start branching ? For instance, for the calendar task `common.api.fossasia.net` and the map task `cmap.api.fossasia.net`.

**Comment by mariobehling** [comment]
done. Please also continue to outline more details for your project here https://github.com/fossasia/api.fossasia.net/issues/11and create an issue for each task you are working on.

**Comment by zyzo** [comment]
These are some ideas that came up : 

* community subscription chart : a line chart showing the total number of  subscribed communities (communities added to [directory.json](https://github.com/fossasia/directory.api.fossasia.net/blob/master/directory.json)) on each time period. The new factor here is time and this information could be retrieved from git commit  history. 

* FOSSASIA API originated from Freifunk API which is used among wireless communities. FOSSASIA is an open-source community, so there are different aspects that could be shared as well. For instance, it's likely that the community has a github/gitlab/git repo, like FOSSASIA. We could collect interesting information from their codebase (number of projects, languages used, last active..).

**Comment by zyzo** [comment]
Another idea : active contribution line chart **per each community**. The chart show contributions count of the community on each time period. The contributions count is the sum of their facebook post, twitter tweets, ics events... and other relevant activities.

**Comment by zyzo** [comment]
@andibraeu @mariobehling What are your thoughts on this ? Is any of these ideas good or I'll keep looking ?

**Comment by andibraeu** [comment]
I think we have enough ideas and tasks
