### ISSUE TITLE
Create Milestones and add features in each milestone

### ISSUE THREAD

**Issue by mariobehling** [fossasia/api.fossasia.net#11]
For Features List refer to https://github.com/fossasia/api.fossasia.net/issues/10

Milestone 1
Due by June 10, 2015

Milestone 2
Due by June 26, 2015

Milestone 3
Due by July 25, 2015

Milestone 4
Due by August 21, 2015

**Comment by zyzo** [comment]
Do the milestones have to be the same ? Based on my project proposal : 

**Milestone 0 : API generator addition** - May 31
(already done)

**Milestone 1: Calendar service** - June 21

* ics parser & merger
* Calendar API 
* community event calendar & community news panel.

**Milestone 2 : Community map enhancement** - July 5

* filter by country / technical areas.
* (using calendar service) add info about latest/upcoming event/news on the map marker for each community.

**Milestone 3 : Statistic chart service** - July 26

* Statistic API
* number of registered communities
* percentage of communities per countries (pie chart)
* percentage of communities per tech area (also pie chart)
* community active period panel (like the one in github), based on news and events.
* number of web services deployed in total, and web services types (pie chart)

**Milestone 4 : API documentation** - August 16

* API docs webapp
* API documentation content (guides, examples)

**Comment by mariobehling** [comment]
@zyzo Thank you. As we are now in the coding stage, we would like to see more details and info on technologies. Your proposal was good to show us you put thoughts into the project, but we are now in the project. A few more points for example.
* I would like to see more features implemented. At the moment especially milestones 3 and 4 seem a bit modest. API documentation is not a milestones. 
* Documentation is a continuous part of a project. 
* Milestone 4 is missing info. Please add additional development to milestone 4 in particular.
* Please also info on testing frameworks and what tests you are planning to add.
* Open Source is not just a top down development system - we are looking for active contributions. What are your cool ideas to implement in this project. Please add some cool stuff for us.

**Comment by andibraeu** [comment]
@zyzo can you please add your tasks to the milestones page? https://github.com/fossasia/api.fossasia.net/milestones

**Comment by zyzo** [comment]
@andibraeu the milestones are updated :) . 
@mariobehling 
The vision I had for API documentation is to build a complete webapp, not just some texts and screenshots. I think it's also very important for the user/community to understand thoroughly our work.

I know that API testing is a continuous part but milestone 4 could be dedicated to add more testing as well. 

About new projects ideas, I added some in #10, we should discuss them in a single place.

**Comment by mariobehling** [comment]
@zyzo Please generate issues based on this list and add each issue into a milestone.

**Comment by andibraeu** [comment]
Done so far, I think @zyzo will do a breakdown on each milestone. Works great for Milestone 1
