### ISSUE TITLE
Ics parser & merger

### ISSUE THREAD

**Issue by zyzo** [fossasia/api.fossasia.net#13]
Create an ics tool to parse & combine Icalendar feeds, provided by communities. Some initiatives can be found here https://github.com/fossasia/common.api.fossasia.net/tree/ical-merger

**Comment by zyzo** [comment]
A demo of the ics debugger tool http://fossasia-api.herokuapp.com/
Follow up [blog post](http://zyzo.github.io/gsoc/fossasia/2015/05/25/fossasia-api-calendar-service.html).

**Comment by zyzo** [comment]
Existing problems / TODO for [ics merger](https://github.com/fossasia/common.api.fossasia.net/blob/ical-merger/ics-collector/debugger/lib/ics-merger.php) : 
* decide what to put on some common "header" fields, for e.g. [PRODID] (https://tools.ietf.org/html/rfc5545#section-3.7.3). The logical thing might be somethiing nonstandard like `-//FOSSASIA//FOSSASIA Calendar//EN` 
* detect redundant events. This happens mainly when a same file is added twice as merger input.
* synchronized merge for ics files with different timezone

**Comment by andibraeu** [comment]
Am Dienstag, den 26.05.2015, 05:55 -0700 schrieb DANG HAI AN:
> Existing problems / TODO for ics merger :
> decide what to put on some common "header" fields, for e.g. PRODID.
> The logical thing might be somethiing nonstandard like 
> -//FOSSASIA//FOSSASIA Calendar//EN
it was great if you can make such things configurable via config file
      * > detect redundant events. This happens mainly when a same file is added twice as merger input.
my suggestion is to first collect all links from (FOSSASIA|Freifunk)
API and then remove duplicate links
      * > synchronized merge for ics files with different timezone
same here, I have 2 ideas: make the timezone configurable, so everyone
who uses the merger can use the favorite timezone. If no timezone is
configured use UTC

**Comment by zyzo** [comment]
Thanks for good advice ! I'll try something out.

**Comment by zyzo** [comment]
Debugging option for merger added on http://fossasia-api.herokuapp.com/
![alt text](http://etud.insa-toulouse.fr/~hadang/img/img.png "Logo Title Text 1")

**Comment by zyzo** [comment]
Added [support](https://github.com/fossasia/common.api.fossasia.net/tree/ical-merger/ics-collector/debugger) for different timezone. The strategy is as follow : 

1. The default timezone is configurable via ics-merger-config.ini
2. Only look for local time to convert (cf. #6) : 
    * if the local time is provided with timezone reference, convert from that timezone to default timezone
    * if not, check for global timezone information (`VTIMEZONE` component and/or `X-WR-TIMEZONE`property). (not yet implemented)

**Comment by zyzo** [comment]
Results : 
 https://github.com/fossasia/common.api.fossasia.net/blob/master/ics-collector/lib/class.iCalReader.php
 https://github.com/fossasia/common.api.fossasia.net/blob/master/ics-collector/lib/ics-merger.php
