### ISSUE TITLE
Calendar API

### ISSUE THREAD

**Issue by zyzo** [fossasia/api.fossasia.net#17]
An ICalendar webservice with support for query parameters

**Comment by zyzo** [comment]
Proposed architecture ![Calendar API architecture](http://etud.insa-toulouse.fr/~hadang/img/CalendarAPI.jpg)

I want to point out some details about this : 
* There are two parts in the architecture : a periodic job to retrieve & update merged ics file, and an API endpoint for users to query. (the user will be mostly us #18 #19)
* The calendar API operates with plain ics files as backend. In the frontend (exposed API) it's possible to have a file type option (ics, json, xml..).

* In the 2nd part, the parser operates with both merged ics and individual community ics because the user can query information about one single community.

Am I missing anything?

**Comment by andibraeu** [comment]
do you have a data format for json and xml events? at the moment I don't understand who will use xml and json?

**Comment by zyzo** [comment]
> do you have a data format for json and xml events

not really, there is http://microformats.org/wiki/hcalendar for extracting ics infos from html, but we're doing the other way around. 

> at the moment I don't understand who will use xml and json?

I just find that having json as a file type option will make it mucg easier to work with js calendar libraries. As a plus, the data won't have to be parsed again.

Of course if the user just want ics feeds to import into their calendar plugins it is possible too.

**Comment by andibraeu** [comment]
works great!
