### ISSUE TITLE
Calendar API : 'from' and 'to' parameters

### ISSUE THREAD

**Issue by zyzo** [fossasia/api.fossasia.net#23]
`From` : return only events happening after 'from' parameter value.
`To` : return only events happening before `to` parameter value.

There are some technical choices that could be discussed : 

* The format of parameter value. What is done right now is the API only accepts parameter with format `YYYY-MM-DD`. The time value (hour, minute) is not compared.
* The ics event's property to compare to. A candidate is `DTSTART`

**Comment by zyzo** [comment]
Now `from` and `to` can also take mixed datetime value, for e.g : 
```
 2015-07-05T00:00:00
```

**Comment by andibraeu** [comment]
works
