### ISSUE TITLE
Deploy Calendar API

### ISSUE THREAD

**Issue by zyzo** [fossasia/api.fossasia.net#25]
Is this possible to have a public url to points to [common.api.fossasia.net/ics-collector/CalendarAPI.php](https://github.com/fossasia/common.api.fossasia.net/blob/dev/ics-collector/CalendarAPI.php) ?

**Comment by andibraeu** [comment]
there you go: http://api.fossasia.net/ics-collector/CalendarAPI.php

**Comment by andibraeu** [comment]
please tell me if you need an update there. ATM it's on dev branch

**Comment by zyzo** [comment]
Thanks !

**Comment by zyzo** [comment]
@andibraeu could you make an update of dev ? I added the missing merged ics file without what the API won't return results

**Comment by andibraeu** [comment]
I made an update

What about the ICS merger? Should I install a cron job to let it run i.e. once per hour? Do you have docs how to do that?

**Comment by andibraeu** [comment]
then we don't need to update a file on github

**Comment by zyzo** [comment]
I'll commit the updater script to run

**Comment by zyzo** [comment]
@andibraeu  The updater file can be found here https://github.com/fossasia/common.api.fossasia.net/blob/dev/ics-collector/lib/ics-updater.php. It requires a valid url to ics-collector.php script. 

Currently I specify the url to the ics-collector of FOSSASIA (http://api.fossasia.net/ics-collector/ics-collector.php) which doesn't return a lot of results. Seems like the ffSummarizedDir.json is missing in ics-collector folder.

For a more interesting set of events data could you modify the link to point to freifunk api ics-collector ? Thank you.

**Comment by andibraeu** [comment]
can you please make the the url  to the ffSummarizedDir configurable? For freifunk and fossasia we also have cronjobs running, creating the summarized dir

**Comment by andibraeu** [comment]
a complete freifunk summary you'll find here: http://freifunk.net/map/ffSummarizedDir.json

**Comment by andibraeu** [comment]
at the moment the merger and updater is configured to use the fossasia summary, but there are as you know only 3  communites

**Comment by zyzo** [comment]
> can you please make the the url to the ffSummarizedDir configurable? For freifunk and fossasia we also have cronjobs running, creating the summarized dir

There is already a variable for this I think , at the [beginning](can you please make the the url to the ffSummarizedDir configurable? For freifunk and fossasia we also have cronjobs running, creating the summarized dir) of ics-collector.php : 
```php
$communities = "./ffSummarizedDir.json";
```
> at the moment the merger and updater is configured to use the fossasia summary, but there are as you know only 3 communites

Yeah the updater points to fossasia ics-collector. This could be configured by a constant : 
```php
const ICS_COLLECTOR_URL = "http://api.fossasia.net/ics-collector/ics-collector.php";
```

Maybe we could use relative url to limit the number of config parameters ?

**Comment by andibraeu** [comment]
Am Dienstag, den 09.06.2015, 14:35 -0700 schrieb DANG HAI AN:
> can you please make the the url to the ffSummarizedDir configurable? 
> For freifunk and fossasia we also have cronjobs running, creating the 
> summarized dir
> There is already a variable for this I think , at the beginning of 
> ics-collector.php :
> 

my idea was to have an external config file as we did for the api
generator, too.
At the end we'll use these tools on several servers and APIs, and we
don't want people to have to edit source code :-)

**Comment by zyzo** [comment]
I made the links to `ics-collector.php` and `ffSummarizedDir.json` configurable via `api-config.ini`. A single config file is better I think.

**Comment by andibraeu** [comment]
works, it's fine like it is
