### ISSUE TITLE
Community timeline as a library

### ISSUE THREAD

**Issue by zyzo** [fossasia/api.fossasia.net#29]
The idea is to have a clean interface, maybe a jquery extension, to allow users to embed the timeline easily in their page : 

```html
<div id="timeline"></div>
<script type="text/javascript" src="community-timeline.js"></script>	
<script>
   $('#timeline').CommunityTimeline(options);
</script>

**Comment by zyzo** [comment]
What options should we have ? I'm thinking : 
   - `source` (community)
   - `from`, `to` to limit initially displayed events  (the default of to will be `today`. Older/newer events could be lazy loaded using ajax)
   - css styles that can't be customized, like `height`

**Comment by andibraeu** [comment]
is it possible to display event details when I click on them?

**Comment by zyzo** [comment]
Yeah I had the same idea with event details. Please checkout issue #35
