### ISSUE TITLE
Community timeline event info

### ISSUE THREAD

**Issue by zyzo** [fossasia/api.fossasia.net#35]
When the user clicks on an event, more detailed informations should be displayed, eitheir with a popup panel or a hover panel. The informations could be : 
   - Start, end datetime
   - Summary
   - Description
   - Location
   -  ..

**Comment by andibraeu** [comment]
other information:
* a link given to the event
* a link to the community itself (via API data)

**Comment by andibraeu** [comment]
the panel already looks good.

there seem to be some minor problems:
1. the location is the location of the first item for every item
1. the event url is never set, it's inactive, but the text is shown

**Comment by zyzo** [comment]
The second bug is because not a lot of events have URL fields http://api.fossasia.net/ics-collector/CalendarAPI.php?source=all&from=now&sort=desc-start&fields=url. Seems like only the link to the community is widely available

**Comment by zyzo** [comment]
Fixed problem 1.
