### ISSUE TITLE
Move community timeline to fossasia repo

### ISSUE THREAD

**Issue by zyzo** [fossasia/api.fossasia.net#37]
Should it be a standalone project or we can combine it to existing repos ?

**Comment by andibraeu** [comment]
where can I find the code? could be a good idea to have an own repo, but I'll take a look on the code first

**Comment by zyzo** [comment]
Hi Andi, the repo is here https://github.com/zyzo/EventsPanel, under Timeline folder. What's the benefit of own repo ? I think that combined repo is better to centralize development effort and easier to keep track of issues.

**Comment by andibraeu** [comment]
what do you exactly mean?

I would create a repo for EventsPanel, not just the timeline folder.

Do you have another suggestion? I.e. moving it to common.api.fossasia.net? I think we should use 1 repo for 1 product, else it's too complicated for commiting and versioning

**Comment by zyzo** [comment]
Som big projects use a unique central repo for different sub-projects. The main benefit I think is to regroup related products that are not very big in size (feed aggregator, mergedrss, collect community, ics-parser, merger). That make them easier to find and avoid to many small projects.

For example I could imagine the api projects ordered in 3 main folders : `service` (feed aggregator, mergedrss, calcollect, ics-parser, ics-merger), `api` (calendar API, map API..) and `ui` (cmap, timeline).

It's just an idea I have and it might be not the best one. For now I think timeline should follow the convention of FOSSASIA and Freifunk API repos. So please go ahead and open a new project for EventsPanel (maybe with a better name, for e.g. `timeline.api.fossasia.net`) ?

**Comment by andibraeu** [comment]
In the past we had one big repo, at the end we decided to split it up:

* api: for specs and generator
* directory: the heart of the api
* cmap: the map as a central component
* feed: the rss merger
* common: for tools and smaller projects

cmap and feed are seperate repos to check them out and work with versions, we should add all sub repos to the api.fossasia.net README

I'll create a timeline repo for now.
