### ISSUE TITLE
Calendar API: Weird values in file head

### ISSUE THREAD

**Issue by andibraeu** [fossasia/api.fossasia.net#40]
see http://api.fossasia.net/ics-collector/CalendarAPI.php?source=all&format=ics&from=now&sort=desc-start&limit=3

```
URL:http:
X-WR-CALNAME:MergedIcs
X-WR-TIMEZONE:EUROPE/Berlin
X-WR-CALDESC:A combined ics feed of Freifunk communities
TRANSP:
X-FROM-URL:http://freifunk.myriapod.de
http://wordpress.org/extend/plugins/nginx-helper/faq/ for more details-->
X-RADICALE-NAME:
TRIGGER:
X-FROM-URL:https://hamburg.freifunk.net
URL:https:<!--Cached using Nginx-Helper on 2015-06-13 18:28:42. It took 32 queries executed in 0,296 seconds.-->
```

**Comment by zyzo** [comment]
This is because the merger merge ics heads without unsetting anything. I will fix this so that only head values from config arrays will appear.

**Comment by zyzo** [comment]
Bug fixed. Could you please do an update to generate new ffMerged.ics ?

**Comment by andibraeu** [comment]
looks good, ics will be merged every 50 minutes

**Comment by zyzo** [comment]
Oh I see. Just for information, how often ffSummarizedDir.json is updated ?

**Comment by andibraeu** [comment]
once an hour I think
