### ISSUE TITLE
Investigate the ICS file format

### ISSUE THREAD

**Issue by andibraeu** [fossasia/api.fossasia.net#6]
* How is it defined?
* How do common clients deal with it?
* How do servers or services create ICS files?
* Are there known problems with some ICS files from certain services? (hint: Outlook/Exchange, Google Calendar, Apple products)

**Comment by zyzo** [comment]
On ics format problem : DTSTART, DTEND, DTSTAMP properties use ICalendar Date-Time property format, which can take 3 forms :

     DTSTART:19970714T133000  ; Local time
     DTSTART:19970714T173000Z ; UTC time
     DTSTART;TZID=America/New_York:19970714T133000 ; Local time and time zone reference 

[One example outlook file](https://github.com/zyzo/ics-tools/blob/master/data/outlook_1.ics#L25) has following format, which is currently not supported by the parser:

     DTSTART;VALUE=DATE:20150409

It is problably a minor case. We should discuss if we want to support things like this coming from Microsoft. Based on http://fileformats.archiveteam.org/ :

> Microsoft Outlook does the typical Microsoft thing of supporting something vaguely resembling the standard but full of quirky incompatibilities. However, in their defense, what they originally supported was vCalendar, a format which is a predecessor of iCalendar and is very similar in structure; when the iCalendar standard was later developed from it by other vendors, Microsoft only partially supported it at first (though support improved in later versions).

**Comment by andibraeu** [comment]
Done
