### ISSUE TITLE
Introducing scrum

### ISSUE THREAD

**Issue by andibraeu** [fossasia/api.fossasia.net#7]
@zyzo Please document what different scrum questions and varieties exist

**Comment by zyzo** [comment]
Hi @andibraeu,

   From what I found scrum method is best suited for team of 5 members  at least. What would be the difference in our case ? For instance, who is the Scrum Master, the Product Owner and the team ? Does it even matter ? 

   What fundamentally change, others than daily logs and task-based development? I'm excited to see this in practice. Do we use any kind of scrum tools?

**Comment by mariobehling** [comment]
Hi @zyzo We are not able to stay with a strict scrum. It is not the goal to train everyone in detail as a scrum master now, but we would like to understand the progress and questions apart from checking on the issues. Please start to answer the three scrum questions every day and send an email to Andi and me. What version of scrum questions do you propose?

**Comment by zyzo** [comment]
@mariobehling Oh, I think I misunderstand Andi's questions at first. About the 3 scrums questions, I can't have better propositions than the basics : 

 1. What did you do yesterday?
 2. What will you do today?
 3. What obstacle did you find in your way?

I don't have any scrum varieties in mind. With a small-scope project like this, I think fast and good communication, frequent delivery, feedbacks and review sessions should be good enough to move forward. I have impression that with a project like this, using scrum tool (define product backlog, sprints..) are nice to have but introduce unecessary overhead and few actual values. (but please remember this is an opinion of an unexperienced on the matter).

**Comment by mariobehling** [comment]
@zyzo Sounds good. Could you start to send us a scum report everyday from now on, please? Please do it at the same time everyday by email. We can switch from time to time to chat as well and as we have more team members we can invite them to this chat.
