### ISSUE TITLE
Postgres vs. JSON schema

### ISSUE THREAD

**Issue by mariobehling** [fossasia/api.fossasia.net#8]
>> zyzo :  I developed this little script https://github.com/zyzo/api-collector to help me collect the freifunk community data & ics files. After executing app.js and ics.js, the ics files are generated under data\ics\. This is quite convenient as it also shows me which link doesn’t work.

>> I will start thinking about a schema to store the ics in a postgre database (as Duke Leto suggests). The schema will be designed with support for these features in mind : show latest event, upcoming event and latest news of each community, filter by name, since, country.

>andi : Why do we want to have it in a postgres database? At the end we need a mixed ICS feed. Maybe we could think about a JSON schema or anything else.

**Comment by zyzo** [comment]
@andibraeu the idea was to save in the database to be able to query/update later. I thought about mongodb at first, but apparently postgre supports json schema now. Anyway, any db that allows flexible schema will do the trick.

**Comment by andibraeu** [comment]
In my optinion we don't need a persitant data store for ics feeds.

The resulting mixed ics feed should be generated from API feeds when we call it. We can maybe cache ics files of communities, in case of an error on their files.

So the intermediate format could be some json for every community (like the summary json from the collector)

Based on that summary json file we can generate a common ICS file, maybe even other things, like event lists etc.

**Comment by zyzo** [comment]
I think it's a question of performance. How much faster querying and filtering in db faster than in js/php ? It it worth the effort ? The data size matters a lot in situations like this. If we want to keep things simple and flexible, we can just use a ics file that combine all relevant data (like ffGeoJson.json)  . But if the plan is to anticipate lot of event traffic (that might span across several years), I think a database may be a better answer.

Either way we need a script executing periodically to get new events. I think other solutions exist (CallDAV, SyncML, hook ..) that we could investigate when the basic is done.

**Comment by andibraeu** [comment]
In general the generated ICS file should only have events from "now" to a given period of time.

But you're right, we should not create the file on download, but we can create it with a cron script. That script will query all ICS feeds from fossasia API or freifunk API and then generates the result.

Keep it simple! :-)

There won't be that much traffic on events, I think most time we need is to gather ICS files from communities
